# CMake generated Testfile for 
# Source directory: /Users/sawah/Documents/ponts/GMM/2eme_semestre/projet_departement/Kalman/Kalman_code/eigen-eigen-5a0156e40feb/blas/testing
# Build directory: /Users/sawah/Documents/ponts/GMM/2eme_semestre/projet_departement/Kalman/Kalman_code/eigen-eigen-5a0156e40feb/build_eigen/blas/testing
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(sblat1 "/Users/sawah/Documents/ponts/GMM/2eme_semestre/projet_departement/Kalman/Kalman_code/eigen-eigen-5a0156e40feb/blas/testing/runblastest.sh" "sblat1" "/Users/sawah/Documents/ponts/GMM/2eme_semestre/projet_departement/Kalman/Kalman_code/eigen-eigen-5a0156e40feb/blas/testing/sblat1.dat")
add_test(sblat2 "/Users/sawah/Documents/ponts/GMM/2eme_semestre/projet_departement/Kalman/Kalman_code/eigen-eigen-5a0156e40feb/blas/testing/runblastest.sh" "sblat2" "/Users/sawah/Documents/ponts/GMM/2eme_semestre/projet_departement/Kalman/Kalman_code/eigen-eigen-5a0156e40feb/blas/testing/sblat2.dat")
add_test(sblat3 "/Users/sawah/Documents/ponts/GMM/2eme_semestre/projet_departement/Kalman/Kalman_code/eigen-eigen-5a0156e40feb/blas/testing/runblastest.sh" "sblat3" "/Users/sawah/Documents/ponts/GMM/2eme_semestre/projet_departement/Kalman/Kalman_code/eigen-eigen-5a0156e40feb/blas/testing/sblat3.dat")
add_test(dblat1 "/Users/sawah/Documents/ponts/GMM/2eme_semestre/projet_departement/Kalman/Kalman_code/eigen-eigen-5a0156e40feb/blas/testing/runblastest.sh" "dblat1" "/Users/sawah/Documents/ponts/GMM/2eme_semestre/projet_departement/Kalman/Kalman_code/eigen-eigen-5a0156e40feb/blas/testing/dblat1.dat")
add_test(dblat2 "/Users/sawah/Documents/ponts/GMM/2eme_semestre/projet_departement/Kalman/Kalman_code/eigen-eigen-5a0156e40feb/blas/testing/runblastest.sh" "dblat2" "/Users/sawah/Documents/ponts/GMM/2eme_semestre/projet_departement/Kalman/Kalman_code/eigen-eigen-5a0156e40feb/blas/testing/dblat2.dat")
add_test(dblat3 "/Users/sawah/Documents/ponts/GMM/2eme_semestre/projet_departement/Kalman/Kalman_code/eigen-eigen-5a0156e40feb/blas/testing/runblastest.sh" "dblat3" "/Users/sawah/Documents/ponts/GMM/2eme_semestre/projet_departement/Kalman/Kalman_code/eigen-eigen-5a0156e40feb/blas/testing/dblat3.dat")
add_test(cblat1 "/Users/sawah/Documents/ponts/GMM/2eme_semestre/projet_departement/Kalman/Kalman_code/eigen-eigen-5a0156e40feb/blas/testing/runblastest.sh" "cblat1" "/Users/sawah/Documents/ponts/GMM/2eme_semestre/projet_departement/Kalman/Kalman_code/eigen-eigen-5a0156e40feb/blas/testing/cblat1.dat")
add_test(cblat2 "/Users/sawah/Documents/ponts/GMM/2eme_semestre/projet_departement/Kalman/Kalman_code/eigen-eigen-5a0156e40feb/blas/testing/runblastest.sh" "cblat2" "/Users/sawah/Documents/ponts/GMM/2eme_semestre/projet_departement/Kalman/Kalman_code/eigen-eigen-5a0156e40feb/blas/testing/cblat2.dat")
add_test(cblat3 "/Users/sawah/Documents/ponts/GMM/2eme_semestre/projet_departement/Kalman/Kalman_code/eigen-eigen-5a0156e40feb/blas/testing/runblastest.sh" "cblat3" "/Users/sawah/Documents/ponts/GMM/2eme_semestre/projet_departement/Kalman/Kalman_code/eigen-eigen-5a0156e40feb/blas/testing/cblat3.dat")
add_test(zblat1 "/Users/sawah/Documents/ponts/GMM/2eme_semestre/projet_departement/Kalman/Kalman_code/eigen-eigen-5a0156e40feb/blas/testing/runblastest.sh" "zblat1" "/Users/sawah/Documents/ponts/GMM/2eme_semestre/projet_departement/Kalman/Kalman_code/eigen-eigen-5a0156e40feb/blas/testing/zblat1.dat")
add_test(zblat2 "/Users/sawah/Documents/ponts/GMM/2eme_semestre/projet_departement/Kalman/Kalman_code/eigen-eigen-5a0156e40feb/blas/testing/runblastest.sh" "zblat2" "/Users/sawah/Documents/ponts/GMM/2eme_semestre/projet_departement/Kalman/Kalman_code/eigen-eigen-5a0156e40feb/blas/testing/zblat2.dat")
add_test(zblat3 "/Users/sawah/Documents/ponts/GMM/2eme_semestre/projet_departement/Kalman/Kalman_code/eigen-eigen-5a0156e40feb/blas/testing/runblastest.sh" "zblat3" "/Users/sawah/Documents/ponts/GMM/2eme_semestre/projet_departement/Kalman/Kalman_code/eigen-eigen-5a0156e40feb/blas/testing/zblat3.dat")
